# 피마인디언 당뇨병

In [13]:
from google.colab import files
import numpy as np
import tensorflow as tf

In [14]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 2021
np.random.seed(seed)
tf.random.set_seed(seed)

### 데이터 전처리

In [4]:
file_uploaded = files.upload()

Saving pima-indians-diabetes.csv to pima-indians-diabetes.csv


In [10]:
filename = list(file_uploaded.keys())[0]

In [11]:
dataset = np.loadtxt(filename,delimiter=',')
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

####정규화

In [44]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X_norm = scale.fit_transform(dataset[:, :-1])
Y = dataset[:, -1]
X.shape, Y.shape

((768, 8), (768,))

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
    X_norm, Y,stratify=Y,random_state = seed
)
X_train.shape,X_test.shape

((576, 8), (192, 8))

### 모델 설계

In [46]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input

In [47]:
model = Sequential([
    Dense(12, input_shape=(8,), activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

### 모델 환경설정

In [48]:
model.compile(
                loss='binary_crossentropy', 
                optimizer='adam', 
                metrics=['accuracy']
            )

### 모델 학습

In [49]:
history = model.fit(X_train,y_train, validation_split=0.2, epochs=200, batch_size=50)

Epoch 1/200
10/10 [==============================] - 1s 23ms/step - loss: 0.7380 - accuracy: 0.4463 - val_loss: 0.7112 - val_accuracy: 0.5172
Epoch 2/200
10/10 [==============================] - 0s 6ms/step - loss: 0.7159 - accuracy: 0.4846 - val_loss: 0.6877 - val_accuracy: 0.5259
Epoch 3/200
10/10 [==============================] - 0s 6ms/step - loss: 0.6876 - accuracy: 0.5383 - val_loss: 0.6714 - val_accuracy: 0.5948
Epoch 4/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6686 - accuracy: 0.6339 - val_loss: 0.6588 - val_accuracy: 0.6466
Epoch 5/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6507 - accuracy: 0.6544 - val_loss: 0.6496 - val_accuracy: 0.6379
Epoch 6/200
10/10 [==============================] - 0s 6ms/step - loss: 0.6400 - accuracy: 0.7029 - val_loss: 0.6417 - val_accuracy: 0.6638
Epoch 7/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6221 - accuracy: 0.7096 - val_loss: 0.6351 - val_accuracy: 0.6724
Epoch 8/200


In [50]:
acc = model.evaluate(X_test, y_test, verbose=2)
print(f"Accuracy: {acc[1]:.4f}")

6/6 - 0s - loss: 0.4995 - accuracy: 0.7760
Accuracy: 0.7760


### 테스트

In [65]:
index = 10
test_data = X_test[index,:].reshape(1,-1)
test_data

array([[-0.54791859,  2.38188392,  0.04624525,  4.92186584, -0.69289057,
         0.34362394,  0.31144581,  2.44704844]])

In [66]:
label = y_test[index]
int(label)

1

In [67]:
pred = model.predict(test_data)
pred

array([[0.6424676]], dtype=float32)

In [68]:
int(pred[0][0] > 0.5)

1